# Generated by Django 4.1.7 on 2024-01-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='added',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='information',
            name='impact',
            field=models.CharField(max_length=500),
        ),
    ]
