# Generated by Django 4.1.7 on 2024-01-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_information_added_alter_information_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='published',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
